version: 0.0.0
commands:
  up:
    cmd: "docker-compose up -d"
    usage: Start the docker-compose containers.
  proxy-up:
    cmd: "docker run -d -p 80:80 -v /var/run/docker.sock:/tmp/docker.sock:ro jwilder/nginx-proxy"
    usage: Run the nginx-proxy container
  stop:
    cmd: "docker-compose stop"
    usage: Stop the docker-compose containers (non-destructive).
  ps:
    cmd: "docker-compose ps"
    usage: List the running docker-compose containers.
  ip:
    cmd: "docker-machine ip default"
    usage: Show the ip address f the default docker machine VM
  reset:
    cmd: "docker-compose stop && docker-compose rm && ahoy up"
    usage: Start the docker compose-containers.
  bash:
    cmd: "docker-compose run {{args}} bash "
    usage: run drush commands in the cli service container.
  behat:
    cmd: "docker exec -it $(docker-compose ps -q web) bash -c 'cd /var/www/test && vendor/behat/behat/bin/behat -p docker {{args}}'"
    usage: Run the behat tests
  behat-init:
    cmd: "docker exec -it $(docker-compose ps -q web) bash -c 'cd /var/www/test && composer install'"
    usage: Inititalize behat.
