<?php
/**
 * @file
 * Code for the custom config feature.
 */

/**
 * Implements hook_help().
 *
 * Displays help and module information.
 *
 * @param path
 *   Which path of the site we're using to display help
 * @param arg
 *   Array that holds the current path as returned from arg() function
 */
function dbmi_help($path, $arg) {
    switch ($path) {
        case "admin/help#dbmi":
            return '<p>' . t("TBD") . '</p>';
            break;
    }
}

include_once 'dbmi.features.inc';

function dbmi_menu() {

    $aItems = array();
        $aItems['dbmi/movie/add'] = array(
            'title' => 'Add Movies',
            'page callback' => 'drupal_get_form',
            'page arguments' => array('form_example'),
            'access callback' => TRUE,
        );
    return $aItems;
}

/**
 * Page callback mapped to the url /dbmi/movie/add
 *
 * @return array
 */
function _page_dbmi() {
    return array(
        '#markup' => '<p>Add Movie</p>
                      <p> There will be a form here</p>'
    );
}

function form_example($form, &$form_state) {

    $form['movie'] = array(
        '#type' => 'fieldset',
        '#title' => t('Movie'),
        '#collapsible' => TRUE,
        '#collapsed' => FALSE,
    );
    $form['movie']['title'] = array(
        '#type' => 'textfield',
        '#title' => t('Title'),
        '#required' => TRUE,
        '#default_value' => "Title",
        '#description' => "Please enter the movie title.",
    );
    $form['movie']['year'] = array(
        '#type' => 'textfield',
        '#title' => t('Year'),
        '#required' => TRUE,
        '#default_value' => "Year",
        '#description' => "Please enter the year the movie was released",
    );

    $form['submit'] = array(
        '#type' => 'submit',
        '#value' => 'SEARCH',
    );
    return $form;

}

function form_example_submit($form_id, &$form_state) {
    $form_state['redirect'] = array( 'http://www.omdbapi.com/?t='.
        $form_state['values']['title'].'&y='.$form_state['values']['year']."&plot=short&r=json",
);
}